### ISSUE TITLE
jade-dashboard not working in ubuntu 16.04

### ISSUE THREAD

**Issue by JPRuehmann** [codesardine/Jadesktop#39]
`/opt/jade/jade-dashboard`

```
Ops something went wrong: No module named j.AK
Traceback (most recent call last):
  File "/opt/jade/jade-dashboard", line 20, in <module>
    import xdg.DesktopEntry
ImportError: No module named DesktopEntry
```

I´ve installed all prerequisites as mentioned
Jade-Application-Kit:
```
sudo -H pip install Jade-Application-Kit
Requirement already satisfied: Jade-Application-Kit in /usr/local/lib/python3.5/dist-packages
```
Jade-menu-data
paper-icon-theme-git
python-xdg:
```
sudo -H pip install xdg
Requirement already satisfied: xdg in /usr/local/lib/python3.5/dist-packages
```
python-gobject:
```
sudo -H pip install gobject
Requirement already satisfied: gobject in /usr/local/lib/python3.5/dist-packages
```

Thanks,

**Comment by codesardine** [comment]
It seems is not finding your modules do you only have 1 version of python installed?
what linux distro you are using? I only tested on manjaro linux.

**Comment by JPRuehmann** [comment]
No 2.7 and 3.5
I am using Kubuntu 16.04 LTS (32Bit)

Tried that but no change.
```
/opt/jade/jade-dashboard
Traceback (most recent call last):
  File "/opt/jade/jade-dashboard", line 20, in <module>
    import xdg.DesktopEntry
ImportError: No module named 'xdg.DesktopEntry'; 'xdg' is not a package
```

**Comment by JPRuehmann** [comment]
I am a Bit further.

```
/opt/jade/jade-dashboard
Icon Not found in this theme --> browser
Icon Not found in this theme --> folder_color_pink
Icon Not found in this theme --> system-reboot
Icon Not found in this theme --> system-hibernate
Icon Not found in this theme --> system-suspend
Icon Not found in this theme --> system-hibernate
Traceback (most recent call last):
  File "/opt/jade/jade-dashboard", line 121, in <module>
    html = Api.openFile(html_file)
AttributeError: type object 'Api' has no attribute 'openFile'

```

**Comment by codesardine** [comment]
Remove Jade-Application-Kit
sudo apt-get -y install python3-pip
sudo -H pip3 install Jade-Application-Kit
I tink that should do it

**Comment by JPRuehmann** [comment]
No, no change.

**Comment by JPRuehmann** [comment]
Does it use its own Theme config or that of the KDE Desktop?

**Comment by codesardine** [comment]
I'm way from the computer, will have a look into it tomorow, on KDE set gtk icon theme for paper icons.

**Comment by JPRuehmann** [comment]
OK, then the Theme errors are gone.

```
/opt/jade/jade-dashboard
Traceback (most recent call last):
  File "/opt/jade/jade-dashboard", line 121, in <module>
    html = Api.openFile(html_file)
AttributeError: type object 'Api' has no attribute 'openFile'

```

**Comment by codesardine** [comment]
There was an older version on pypi remove Jade-Application-kit and install again (dont upgrade)

**Comment by JPRuehmann** [comment]
Thanks, now it works.
